// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kulinsky/gotestexample/internal/app/command (interfaces: Repository,IDProvider)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/create_short_url_cmd.go -package=mocks -mock_names=Repository=MockCmdRepo,IDProvider=MockIDProvider github.com/kulinsky/gotestexample/internal/app/command Repository,IDProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCmdRepo is a mock of Repository interface.
type MockCmdRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCmdRepoMockRecorder
}

// MockCmdRepoMockRecorder is the mock recorder for MockCmdRepo.
type MockCmdRepoMockRecorder struct {
	mock *MockCmdRepo
}

// NewMockCmdRepo creates a new mock instance.
func NewMockCmdRepo(ctrl *gomock.Controller) *MockCmdRepo {
	mock := &MockCmdRepo{ctrl: ctrl}
	mock.recorder = &MockCmdRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCmdRepo) EXPECT() *MockCmdRepoMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockCmdRepo) Save(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCmdRepoMockRecorder) Save(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCmdRepo)(nil).Save), arg0, arg1, arg2)
}

// MockIDProvider is a mock of IDProvider interface.
type MockIDProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIDProviderMockRecorder
}

// MockIDProviderMockRecorder is the mock recorder for MockIDProvider.
type MockIDProviderMockRecorder struct {
	mock *MockIDProvider
}

// NewMockIDProvider creates a new mock instance.
func NewMockIDProvider(ctrl *gomock.Controller) *MockIDProvider {
	mock := &MockIDProvider{ctrl: ctrl}
	mock.recorder = &MockIDProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDProvider) EXPECT() *MockIDProviderMockRecorder {
	return m.recorder
}

// Provide mocks base method.
func (m *MockIDProvider) Provide() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provide")
	ret0, _ := ret[0].(string)
	return ret0
}

// Provide indicates an expected call of Provide.
func (mr *MockIDProviderMockRecorder) Provide() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provide", reflect.TypeOf((*MockIDProvider)(nil).Provide))
}
